"""oauth

Revision ID: 0afac3d3ede6
Revises: 3cb6deba18e0
Create Date: 2023-06-30 19:12:11.060274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0afac3d3ede6'
down_revision = '3cb6deba18e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('Description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('token', sa.String(length=256), nullable=False))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.drop_index('ix_user_email')
        batch_op.create_unique_constraint(None, ['token'])
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('group_id')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_ibfk_1', 'group', ['group_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('token')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('Description',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
